 [build-system]
 requires = [
     "setuptools>=42",
     "wheel"
 ]
 build-backend = "setuptools.build_meta"

[project]
name = "exm-toolbox"
authors = [{name = "Emma", email = "emmabesier@g.harvard.edu"}]
dynamic = ["version", "description"]
